default:
  vibration:
    max_warn: 30.0
    max_critical: 60.0
    clip_warn: 1.0
    clip_critical: 80.0
  compass:
    range_warn: 220.0
    range_critical: 420.0
    std_warn: 80.0
    std_critical: 160.0
  battery:
    volt_min_warn: 10.8
    volt_min_critical: 9.8
    volt_range_warn: 1.0
    volt_range_critical: 2.0
    curr_max_warn: 45.0
    curr_max_critical: 65.0
  gps:
    fix_pct_warn: 90.0
    fix_pct_critical: 70.0
    nsats_min_warn: 8.0
    nsats_min_critical: 5.0
    hdop_max_warn: 2.5
    hdop_max_critical: 4.0
  motor:
    spread_mean_warn: 120.0
    spread_mean_critical: 220.0
    spread_max_warn: 220.0
    spread_max_critical: 350.0
    output_std_warn: 90.0
    output_std_critical: 150.0
  attitude:
    roll_std_warn: 8.0
    roll_std_critical: 15.0
    pitch_std_warn: 8.0
    pitch_std_critical: 15.0
    roll_max_warn: 30.0
    roll_max_critical: 45.0
    pitch_max_warn: 30.0
    pitch_max_critical: 45.0
    desroll_err_warn: 10.0
    desroll_err_critical: 20.0

copter:
  attitude:
    roll_std_warn: 7.0
    roll_std_critical: 13.0
    pitch_std_warn: 7.0
    pitch_std_critical: 13.0

plane:
  gps:
    fix_pct_warn: 92.0
    fix_pct_critical: 75.0
  vibration:
    max_warn: 35.0
    max_critical: 70.0

rover:
  attitude:
    roll_max_warn: 22.0
    roll_max_critical: 35.0
  gps:
    nsats_min_warn: 6.0
    nsats_min_critical: 4.0

sub:
  gps:
    fix_pct_warn: 0.0
    fix_pct_critical: 0.0
  compass:
    range_warn: 260.0
    range_critical: 500.0
